"""Extra content part 2: geometry new topics."""

def sec(sid, title, body):
    return f'<div class="content-section" id="{sid}"><h2>{title}</h2>{body}</div>'

def p(*texts):
    return "".join(f"<p>{t}</p>" for t in texts)

EXTRA2 = {}

EXTRA2["geometry/surface-area"] = [sec("indepth","In Depth", p(
    "Surface area measures the total area of the outer surface of a three-dimensional solid. For polyhedra, it is the sum of the areas of all faces. For curved surfaces, it requires integration.",
    "Key formulas: sphere \\(SA=4\\pi r^2\\), cylinder (lateral) \\(SA=2\\pi rh\\), cone (lateral) \\(SA=\\pi r l\\) where \\(l=\\sqrt{r^2+h^2}\\) is the slant height. These are derived by 'unrolling' the surface into a flat shape.",
    "For a surface of revolution generated by rotating \\(y=f(x)\\) about the \\(x\\)-axis: \\(SA=2\\pi\\int_a^b f(x)\\sqrt{1+[f'(x)]^2}\\,dx\\). The factor \\(\\sqrt{1+[f'(x)]^2}\\) accounts for the arc length element.",
    "The isoperimetric inequality in 3D: among all surfaces enclosing a fixed volume \\(V\\), the sphere minimizes surface area \\(SA=4\\pi r^2\\) where \\(V=\\frac{4}{3}\\pi r^3\\). This explains why soap bubbles are spherical — surface tension minimizes surface area for a given enclosed volume.",
    "Surface area is critical in engineering and biology. Heat transfer rate is proportional to surface area (Newton's law of cooling). The surface-to-volume ratio \\(SA/V\\) decreases as objects scale up, limiting cell size and explaining why small animals lose heat faster relative to their mass."
))]

EXTRA2["geometry/angle"] = [sec("indepth","In Depth", p(
    "An angle is formed by two rays sharing a common endpoint (vertex). Angles are measured in degrees (full rotation = 360°) or radians (full rotation = \\(2\\pi\\)). The radian measure of an angle equals the arc length it subtends on a unit circle, making radians the natural unit for calculus.",
    "Angle classification: acute (0°–90°), right (90°), obtuse (90°–180°), straight (180°), reflex (180°–360°). Complementary angles sum to 90°; supplementary angles sum to 180°; vertical angles (formed by two intersecting lines) are equal.",
    "In a polygon, the sum of interior angles of an \\(n\\)-gon is \\((n-2)\\cdot180°\\). For a triangle: 180°. For a quadrilateral: 360°. The exterior angle of a polygon equals the sum of the two non-adjacent interior angles (for triangles) or \\(360°/n\\) for regular \\(n\\)-gons.",
    "Angles in circles: a central angle equals the arc it intercepts. An inscribed angle equals half the intercepted arc. The angle in a semicircle is always 90° (Thales' theorem). Tangent-chord angles equal half the intercepted arc.",
    "In trigonometry, angles beyond 360° and negative angles are handled by the unit circle definition. The reference angle is the acute angle between the terminal side and the \\(x\\)-axis, used to evaluate trig functions in any quadrant using the ASTC (All Students Take Calculus) sign rule."
))]

EXTRA2["geometry/distance-formula"] = [sec("indepth","In Depth", p(
    "The distance formula \\(d=\\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}\\) is a direct application of the Pythagorean theorem in the coordinate plane. It extends to 3D: \\(d=\\sqrt{(x_2-x_1)^2+(y_2-y_1)^2+(z_2-z_1)^2}\\), and to \\(n\\) dimensions: \\(d=\\sqrt{\\sum_{i=1}^n(b_i-a_i)^2}\\).",
    "The midpoint formula \\(M=((x_1+x_2)/2,(y_1+y_2)/2)\\) gives the point equidistant from both endpoints. It generalizes to the centroid of \\(n\\) points: \\(\\bar{x}=\\frac{1}{n}\\sum x_i\\), \\(\\bar{y}=\\frac{1}{n}\\sum y_i\\).",
    "Distance from a point \\((x_0,y_0)\\) to a line \\(ax+by+c=0\\): \\(d=|ax_0+by_0+c|/\\sqrt{a^2+b^2}\\). This formula is derived by finding the foot of the perpendicular from the point to the line.",
    "In metric spaces, the distance function (metric) must satisfy: non-negativity, identity of indiscernibles, symmetry, and the triangle inequality \\(d(A,C)\\leq d(A,B)+d(B,C)\\). Different metrics on the same set give different geometries: the taxicab metric \\(d=|x_2-x_1|+|y_2-y_1|\\) models city-block distances.",
    "Applications: nearest-neighbor algorithms in machine learning use distance to classify points. GPS systems compute distances on the Earth's surface using the haversine formula (spherical geometry). Computer graphics use distance functions (signed distance fields) for rendering and collision detection."
))]

EXTRA2["geometry/solid-geometry"] = [sec("indepth","In Depth", p(
    "Solid geometry studies three-dimensional figures: polyhedra (bounded by flat faces), curved solids (spheres, cylinders, cones), and combinations. Euler's formula for convex polyhedra \\(V-E+F=2\\) (vertices minus edges plus faces equals 2) is a topological invariant — it holds for any convex polyhedron regardless of shape.",
    "The five Platonic solids — tetrahedron (4 triangular faces), cube (6 square faces), octahedron (8 triangular faces), dodecahedron (12 pentagonal faces), icosahedron (20 triangular faces) — are the only convex polyhedra with all faces congruent regular polygons. Plato associated them with the classical elements.",
    "Volume formulas: sphere \\(V=\\frac{4}{3}\\pi r^3\\), cylinder \\(V=\\pi r^2 h\\), cone \\(V=\\frac{1}{3}\\pi r^2 h\\), pyramid \\(V=\\frac{1}{3}Bh\\) (\\(B\\) = base area). The factor \\(1/3\\) in cone and pyramid volumes follows from Cavalieri's principle.",
    "Cross-sections of 3D solids reveal their internal structure. Slicing a sphere with a plane gives a circle. Slicing a cone gives the conic sections: circle, ellipse, parabola, or hyperbola depending on the angle. This connection between 3D geometry and 2D curves is fundamental to analytic geometry.",
    "In engineering, solid geometry underlies CAD (computer-aided design), finite element analysis, and 3D printing. Constructive solid geometry (CSG) builds complex shapes by combining simple primitives using Boolean operations (union, intersection, difference)."
))]

EXTRA2["geometry/sphere"] = [sec("indepth","In Depth", p(
    "A sphere is the set of all points in 3D space equidistant from a center. Its surface area \\(SA=4\\pi r^2\\) and volume \\(V=\\frac{4}{3}\\pi r^3\\) were first derived by Archimedes, who considered this his greatest achievement. The ratio \\(SA/V=3/r\\) decreases as \\(r\\) increases.",
    "The equation of a sphere with center \\((a,b,c)\\) and radius \\(r\\): \\((x-a)^2+(y-b)^2+(z-c)^2=r^2\\). The unit sphere (\\(r=1\\), centered at origin) is fundamental in mathematics — it is the domain of spherical harmonics and the setting for spherical trigonometry.",
    "Great circles are the largest circles on a sphere, formed by planes through the center. The shortest path between two points on a sphere (geodesic) lies on a great circle. This is why transoceanic flights follow curved paths on a flat map — they are following great circle routes.",
    "Spherical coordinates \\((\\rho,\\theta,\\phi)\\) parameterize 3D space: \\(x=\\rho\\sin\\phi\\cos\\theta\\), \\(y=\\rho\\sin\\phi\\sin\\theta\\), \\(z=\\rho\\cos\\phi\\). The Jacobian is \\(\\rho^2\\sin\\phi\\), so \\(dV=\\rho^2\\sin\\phi\\,d\\rho\\,d\\theta\\,d\\phi\\). These coordinates simplify integrals over spherical regions.",
    "The sphere has the highest symmetry of any 3D object — its symmetry group is O(3), the group of all orthogonal transformations. In physics, spherical symmetry simplifies problems enormously: gravitational and electric fields of spherically symmetric objects depend only on distance from the center."
))]

EXTRA2["geometry/polyhedron"] = [sec("indepth","In Depth", p(
    "A polyhedron is a 3D solid bounded by flat polygonal faces. Euler's formula \\(V-E+F=2\\) holds for all convex polyhedra and is a topological result — it depends only on the connectivity, not the shape. For a torus-shaped polyhedron, \\(V-E+F=0\\).",
    "Archimedean solids are convex polyhedra with regular polygonal faces (not all the same type) and identical vertices. There are 13 of them, including the truncated icosahedron (the soccer ball pattern) and the cuboctahedron. They generalize the Platonic solids.",
    "Dual polyhedra: every polyhedron has a dual obtained by swapping vertices and faces. The dual of the cube is the octahedron; the dual of the dodecahedron is the icosahedron; the tetrahedron is self-dual. Duality preserves Euler's formula.",
    "In crystallography, the 14 Bravais lattices and 230 space groups classify all possible crystal structures. The unit cells are polyhedra that tile 3D space. In chemistry, molecular geometry is described by polyhedra: methane (tetrahedral), sulfur hexafluoride (octahedral), buckminsterfullerene (truncated icosahedron).",
    "Convex hull algorithms find the smallest convex polyhedron containing a set of points. This is fundamental in computational geometry, with applications in collision detection, shape analysis, and data visualization."
))]

EXTRA2["geometry/similarity"] = [sec("indepth","In Depth", p(
    "Two figures are similar if one can be obtained from the other by a combination of rotation, reflection, translation, and uniform scaling. Similar figures have the same shape but possibly different sizes. The ratio of corresponding lengths is the scale factor \\(k\\); areas scale by \\(k^2\\); volumes scale by \\(k^3\\).",
    "AA (Angle-Angle) similarity: two triangles are similar if two pairs of corresponding angles are equal. Since angle sums are 180°, two equal angles force the third to be equal too. SAS and SSS similarity criteria provide alternatives.",
    "The basic proportionality theorem (Thales): a line parallel to one side of a triangle divides the other two sides proportionally. This is the foundation of similar triangle proofs and is used in constructions and proofs throughout geometry.",
    "Similar triangles appear in indirect measurement: the height of a tall object can be found by comparing the shadow lengths of the object and a known reference. This method was used by Thales to measure the height of the Great Pyramid.",
    "In trigonometry, the trig ratios (sin, cos, tan) are defined for right triangles and depend only on the angle, not the size — because all right triangles with the same acute angle are similar. This is why trig functions are well-defined."
))]

EXTRA2["geometry/congruence"] = [sec("indepth","In Depth", p(
    "Two figures are congruent if one can be obtained from the other by rigid motions (isometries): translations, rotations, and reflections. Congruent figures have identical shape and size. The congruence criteria for triangles — SSS, SAS, ASA, AAS, and HL (for right triangles) — are the workhorses of Euclidean proof.",
    "The SAS congruence criterion: if two sides and the included angle of one triangle equal the corresponding parts of another, the triangles are congruent. This is Euclid's Proposition 4 and is the basis for many geometric proofs.",
    "CPCTC (Corresponding Parts of Congruent Triangles are Congruent) is the standard conclusion after proving triangles congruent. It allows deducing that specific angles or sides are equal, which is often the goal of a proof.",
    "In abstract algebra, congruence generalizes to equivalence relations. Two integers are congruent modulo \\(n\\) if they differ by a multiple of \\(n\\). Two matrices are congruent if one can be obtained from the other by a congruence transformation \\(A\\mapsto P^TAP\\).",
    "Rigid motions form a group under composition — the Euclidean group E(n). In 2D, every rigid motion is a translation, rotation, reflection, or glide reflection. This classification is used in crystallography to describe the symmetries of wallpaper patterns (17 wallpaper groups)."
))]

EXTRA2["geometry/plane-geometry"] = [sec("indepth","In Depth", p(
    "Plane geometry (Euclidean geometry in 2D) is built on Euclid's five postulates. The first four are uncontroversial; the fifth (parallel postulate) — through a point not on a line, exactly one parallel line exists — was debated for centuries. Replacing it gives non-Euclidean geometries.",
    "Key theorems: the angle sum of a triangle is 180° (follows from the parallel postulate). The exterior angle of a triangle equals the sum of the two non-adjacent interior angles. The Pythagorean theorem holds in Euclidean geometry but fails in spherical and hyperbolic geometry.",
    "Circles and lines: two distinct points determine a unique line. Three non-collinear points determine a unique circle. A line and circle intersect in 0, 1, or 2 points. Two distinct circles intersect in 0, 1, or 2 points.",
    "Transformations in the plane: translations (shift), rotations (turn about a point), reflections (flip over a line), dilations (scale from a center). Compositions of these generate all similarities and isometries. The group of isometries of the plane is the Euclidean group.",
    "Coordinate geometry (analytic geometry) assigns coordinates to points, converting geometric problems into algebraic ones. This approach, introduced by Descartes and Fermat, unified algebra and geometry and enabled the development of calculus."
))]

EXTRA2["geometry/euclidean-geometry"] = [sec("indepth","In Depth", p(
    "Euclidean geometry, codified in Euclid's Elements (c. 300 BCE), is the geometry of flat space. It is built from five postulates and uses deductive proof to derive all theorems. The Elements contains 465 propositions and remained the standard mathematics textbook for over 2000 years.",
    "The parallel postulate (fifth postulate) is logically independent of the other four. In the 19th century, Bolyai, Lobachevsky, and Riemann showed that consistent geometries exist where the parallel postulate fails. Hyperbolic geometry (infinitely many parallels) and elliptic geometry (no parallels) are the two alternatives.",
    "Euclidean geometry is the geometry of everyday experience at human scales. At cosmological scales, spacetime is curved (general relativity), and Euclidean geometry is only an approximation. At quantum scales, the concept of a definite position breaks down.",
    "Hilbert's axioms (1899) gave a rigorous modern foundation for Euclidean geometry, filling gaps in Euclid's original treatment. Hilbert identified 20 axioms in five groups: incidence, betweenness, congruence, continuity, and parallelism.",
    "Computational geometry applies Euclidean geometry to algorithms: convex hull, Voronoi diagrams, Delaunay triangulation, and polygon intersection. These algorithms underlie GIS, robotics, computer graphics, and mesh generation for finite element analysis."
))]

EXTRA2["geometry/analytic-geometry"] = [sec("indepth","In Depth", p(
    "Analytic geometry (coordinate geometry) represents geometric objects by algebraic equations. Introduced by Descartes and Fermat in the 17th century, it unified algebra and geometry and provided the foundation for calculus.",
    "Lines in the plane: slope-intercept form \\(y=mx+b\\), point-slope form \\(y-y_1=m(x-x_1)\\), standard form \\(Ax+By=C\\), parametric form \\((x,y)=(x_0+t\\cos\\theta, y_0+t\\sin\\theta)\\). Each form is convenient for different purposes.",
    "Conic sections are the curves obtained by intersecting a cone with a plane: circle \\(x^2+y^2=r^2\\), ellipse \\(x^2/a^2+y^2/b^2=1\\), parabola \\(y=ax^2\\), hyperbola \\(x^2/a^2-y^2/b^2=1\\). The general second-degree equation \\(Ax^2+Bxy+Cy^2+Dx+Ey+F=0\\) represents a conic; the discriminant \\(B^2-4AC\\) determines the type.",
    "In 3D, planes are described by \\(ax+by+cz=d\\) where \\((a,b,c)\\) is the normal vector. Lines in 3D are described parametrically: \\((x,y,z)=(x_0+at, y_0+bt, z_0+ct)\\). The distance between skew lines requires the cross product.",
    "Analytic geometry extends to higher dimensions naturally. In \\(\\mathbb{R}^n\\), hyperplanes (codimension-1 subspaces) are described by linear equations, and quadric hypersurfaces by quadratic equations. This generalization is the foundation of linear algebra and machine learning."
))]

EXTRA2["geometry/differential-geometry"] = [sec("indepth","In Depth", p(
    "Differential geometry applies calculus to study curves and surfaces. A smooth curve in \\(\\mathbb{R}^3\\) is described by its curvature \\(\\kappa\\) (how fast it bends) and torsion \\(\\tau\\) (how fast it twists out of a plane). The Frenet–Serret formulas relate the tangent, normal, and binormal vectors.",
    "For surfaces, the first fundamental form measures distances and angles on the surface (intrinsic geometry). The second fundamental form measures how the surface curves in the ambient space (extrinsic geometry). The Gaussian curvature \\(K = \\kappa_1\\kappa_2\\) (product of principal curvatures) is intrinsic — it can be measured by creatures living on the surface.",
    "Gauss's Theorema Egregium ('remarkable theorem'): Gaussian curvature is preserved by isometries (distance-preserving maps). This means you cannot flatten a sphere without distortion — explaining why flat maps of the Earth always distort distances or areas.",
    "The Gauss–Bonnet theorem connects geometry and topology: \\(\\iint_S K\\,dA + \\oint_{\\partial S}\\kappa_g\\,ds = 2\\pi\\chi(S)\\) where \\(\\chi\\) is the Euler characteristic. For a closed surface, \\(\\iint K\\,dA = 2\\pi\\chi\\). This means the total curvature of a sphere is always \\(4\\pi\\), regardless of its shape.",
    "Riemannian geometry generalizes differential geometry to abstract manifolds with a metric tensor. Einstein's general relativity describes gravity as the curvature of 4D spacetime — a Riemannian (actually pseudo-Riemannian) manifold. The geodesics of this curved spacetime are the paths of freely falling objects."
))]

EXTRA2["geometry/conic-sections"] = [sec("indepth","In Depth", p(
    "Conic sections are the curves formed by intersecting a double cone with a plane. Depending on the angle: a horizontal cut gives a circle, a tilted cut gives an ellipse, a cut parallel to the side gives a parabola, and a steeper cut gives a hyperbola. A degenerate cut through the apex gives a point, line, or pair of lines.",
    "The unified focus-directrix definition: a conic is the locus of points where the ratio of distance to a focus and distance to a directrix equals the eccentricity \\(e\\). Circle: \\(e=0\\). Ellipse: \\(0<e<1\\). Parabola: \\(e=1\\). Hyperbola: \\(e>1\\).",
    "In polar coordinates with focus at origin: \\(r = \\ell/(1-e\\cos\\theta)\\) where \\(\\ell\\) is the semi-latus rectum. This single formula describes all conics and is used in orbital mechanics — Kepler's first law states that planetary orbits are conics with the Sun at a focus.",
    "The general second-degree equation \\(Ax^2+Bxy+Cy^2+Dx+Ey+F=0\\) represents a conic. The discriminant \\(\\Delta=B^2-4AC\\) classifies it: \\(\\Delta<0\\) (ellipse/circle), \\(\\Delta=0\\) (parabola), \\(\\Delta>0\\) (hyperbola). Rotation by angle \\(\\theta=\\frac{1}{2}\\arctan(B/(A-C))\\) eliminates the \\(xy\\) term.",
    "Reflective properties make conics useful in optics and engineering: parabolic mirrors focus parallel rays to a point (telescopes, satellite dishes); elliptical mirrors reflect from one focus to the other (whispering galleries, lithotripsy); hyperbolic mirrors appear in Cassegrain telescopes."
))]

EXTRA2["geometry/geometric-constructions"] = [sec("indepth","In Depth", p(
    "Classical geometric constructions use only a compass and straightedge (unmarked ruler). The three famous unsolved problems of antiquity — squaring the circle, doubling the cube, and trisecting an angle — were proved impossible in the 19th century using Galois theory.",
    "Constructible numbers are those reachable from 0 and 1 by a finite sequence of additions, subtractions, multiplications, divisions, and square roots. A regular \\(n\\)-gon is constructible if and only if \\(n=2^k p_1 p_2\\cdots p_m\\) where the \\(p_i\\) are distinct Fermat primes (\\(3, 5, 17, 257, 65537\\)).",
    "Squaring the circle requires constructing \\(\\sqrt{\\pi}\\), but \\(\\pi\\) is transcendental (Lindemann, 1882) — not a root of any polynomial with rational coefficients — so it is not constructible. Doubling the cube requires constructing \\(\\sqrt[3]{2}\\), which has degree 3 over \\(\\mathbb{Q}\\) and is not constructible.",
    "Trisecting an angle is generally impossible: trisecting 60° would require constructing \\(\\cos 20°\\), which satisfies \\(8x^3-6x-1=0\\), an irreducible cubic over \\(\\mathbb{Q}\\). Since its degree is 3 (not a power of 2), it is not constructible.",
    "Modern compass-and-straightedge constructions are used in architecture and design for their aesthetic precision. Computer-aided geometric design (CAGD) uses Bézier curves and B-splines — smooth curves defined by control points — as the modern analogue of classical constructions."
))]

EXTRA2["geometry/quadrilateral"] = [sec("indepth","In Depth", p(
    "A quadrilateral is a polygon with four sides. The sum of interior angles is always 360°. Special quadrilaterals form a hierarchy: parallelogram (opposite sides parallel) → rectangle (right angles) → rhombus (equal sides) → square (right angles and equal sides). Trapezoids have exactly one pair of parallel sides.",
    "Properties of parallelograms: opposite sides are equal and parallel, opposite angles are equal, diagonals bisect each other. The area equals base times height: \\(A=bh\\). For a rhombus, \\(A=\\frac{1}{2}d_1d_2\\) (half the product of diagonals).",
    "Cyclic quadrilaterals (inscribed in a circle) satisfy Ptolemy's theorem: \\(AC\\cdot BD = AB\\cdot CD + AD\\cdot BC\\) (product of diagonals equals sum of products of opposite sides). Brahmagupta's formula gives the area: \\(A=\\sqrt{(s-a)(s-b)(s-c)(s-d)}\\) where \\(s\\) is the semi-perimeter.",
    "The midpoint quadrilateral (Varignon's theorem): connecting the midpoints of any quadrilateral's sides forms a parallelogram. Its area is half the original quadrilateral's area.",
    "In coordinate geometry, a quadrilateral's area can be computed by the shoelace formula: \\(A=\\frac{1}{2}|x_1(y_2-y_4)+x_2(y_3-y_1)+x_3(y_4-y_2)+x_4(y_1-y_3)|\\). This generalizes to any polygon."
))]

EXTRA2["geometry/line-geometry"] = [sec("indepth","In Depth", p(
    "A line is an infinite, straight, one-dimensional figure extending in both directions. In Euclidean geometry, two distinct points determine a unique line. Lines are the simplest geometric objects and the building blocks of all polygonal geometry.",
    "In the coordinate plane, a line is described by a linear equation \\(ax+by=c\\). The slope \\(m=(y_2-y_1)/(x_2-x_1)\\) measures steepness. Parallel lines have equal slopes; perpendicular lines have slopes satisfying \\(m_1m_2=-1\\).",
    "The distance from a point \\((x_0,y_0)\\) to the line \\(ax+by+c=0\\) is \\(d=|ax_0+by_0+c|/\\sqrt{a^2+b^2}\\). This formula is derived by finding the foot of the perpendicular from the point to the line.",
    "In 3D, a line is described parametrically: \\((x,y,z)=(x_0+at, y_0+bt, z_0+ct)\\) where \\((a,b,c)\\) is the direction vector. Two lines in 3D may be parallel, intersecting, or skew (neither parallel nor intersecting). The distance between skew lines uses the cross product.",
    "Projective geometry extends Euclidean geometry by adding 'points at infinity' where parallel lines meet. In projective geometry, any two distinct lines intersect (in exactly one point), simplifying many theorems. Projective transformations (homographies) are used in computer vision for perspective correction."
))]

EXTRA2["geometry/transformation-geometry"] = [sec("indepth","In Depth", p(
    "Geometric transformations map the plane (or space) to itself. Isometries preserve distances: translations, rotations, reflections, and glide reflections. Similarities preserve shape but not size (add uniform scaling). Affine transformations preserve parallelism (add non-uniform scaling and shear). Projective transformations preserve collinearity.",
    "Every isometry of the plane is a composition of at most three reflections. Translations are compositions of two reflections in parallel lines; rotations are compositions of two reflections in intersecting lines; glide reflections are compositions of three reflections.",
    "The symmetry group of a figure consists of all isometries that map the figure to itself. A regular \\(n\\)-gon has dihedral group \\(D_n\\) as its symmetry group (\\(n\\) rotations and \\(n\\) reflections). The symmetry group of a circle is the infinite group O(2).",
    "In linear algebra, linear transformations of \\(\\mathbb{R}^n\\) are represented by matrices. Rotation by \\(\\theta\\) in 2D: \\([[\\cos\\theta,-\\sin\\theta],[\\sin\\theta,\\cos\\theta]]\\). Reflection over the \\(x\\)-axis: \\([[1,0],[0,-1]]\\). Scaling by \\(k\\): \\(kI\\). Composition corresponds to matrix multiplication.",
    "Transformations are fundamental in computer graphics (model-view-projection pipeline), robotics (forward and inverse kinematics), and physics (symmetry transformations correspond to conservation laws via Noether's theorem)."
))]

EXTRA2["geometry/point-geometry"] = [sec("indepth","In Depth", p(
    "A point is the most fundamental geometric object — it has position but no size, dimension, or extent. In Euclidean geometry, points are undefined primitives; all other objects are defined in terms of them. In coordinate geometry, a point in \\(\\mathbb{R}^n\\) is an ordered \\(n\\)-tuple of real numbers.",
    "Special points associated with triangles: centroid (intersection of medians, center of mass), circumcenter (equidistant from vertices, center of circumscribed circle), incenter (equidistant from sides, center of inscribed circle), orthocenter (intersection of altitudes). The Euler line passes through the centroid, circumcenter, and orthocenter.",
    "The nine-point circle passes through nine special points of a triangle: the midpoints of the three sides, the feet of the three altitudes, and the midpoints of the segments from each vertex to the orthocenter. Its center lies on the Euler line, midway between the circumcenter and orthocenter.",
    "In topology, a point is a 0-dimensional manifold. Point-set topology studies properties of spaces defined in terms of open sets, without reference to distance. Compactness, connectedness, and continuity are topological properties that generalize geometric intuition.",
    "Fixed points of transformations are points mapped to themselves. The Brouwer fixed-point theorem guarantees that any continuous map from a closed ball to itself has at least one fixed point. This has applications in economics (Nash equilibrium existence) and differential equations."
))]
